//! TypeScript 类型生成模块
//!
//! 此模块为所有 API 相关类型实现 TS trait，用于自动生成 TypeScript 类型定义。
//!
//! 注意：由于我们使用 #[derive(TS)] 宏，不需要手动实现 TS trait。
//! 此文件保留用于未来可能的自定义类型生成逻辑。

#[cfg(feature = "typescript-export")]
use ts_rs::TS;

/// 导出函数：生成所有类型的 TypeScript 定义
#[cfg(feature = "typescript-export")]
pub fn export_types() -> String {
    // ts-rs 会自动处理所有带有 #[derive(TS)] 的类型
    // 我们只需要在 build.rs 中调用 ts-rs 的生成功能
    String::new()
}

/// 导出所有类型到指定目录
#[cfg(feature = "typescript-export")]
pub fn write_types_to_file(output_path: &std::path::Path) -> std::io::Result<()> {
    use std::fs::File;
    use std::io::Write;

    // 确保输出目录存在
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // 使用 ts-rs 的内置生成功能
    // 这里我们返回空字符串，实际的生成会在 build.rs 中完成
    let mut file = File::create(output_path)?;
    file.write_all(b"// TypeScript types will be generated by ts-rs in build.rs\n")?;
    file.write_all(b"\n")?;

    Ok(())
}
