// Core type definitions for Elizabeth platform

// Import auto-generated types from Rust backend
// These types are automatically generated by ts-rs during build
// To regenerate: cargo build --package elizabeth-board --features typescript-export
export * from '../types/generated/api.types';

import { buildContentAssetPath, buildContentPreviewPath } from "./utils/file-links";
import type {
  ContentType as GeneratedContentType,
  RoomView as GeneratedRoomView,
  RoomContentView as GeneratedRoomContentView,
  IssueTokenResponse as GeneratedIssueTokenResponse,
  CreateRoomResponse as GeneratedCreateRoomResponse,
  UploadPreparationResponse as GeneratedUploadPreparationResponse,
  ValidateTokenResponse as GeneratedValidateTokenResponse,
} from '../types/generated/api.types';

// ============================================================================
// Backend API Types (aligned with Rust backend)
// ============================================================================

/**
 * Content Type enumeration (matches backend ContentType enum)
 */
export enum ContentType {
  Text = 0,
  Image = 1,
  File = 2,
  Url = 3,
}

/**
 * Backend ContentType response format (tagged enum)
 */
export type BackendContentType = GeneratedContentType;

/**
 * Convert backend ContentType to frontend enum
 */
export function parseContentType(
  backendType: BackendContentType | number | undefined | null,
): ContentType {
  // Fallback when backend omits content_type (e.g., during upload pipeline)
  if (backendType == null) {
    return ContentType.File;
  }
  if (typeof backendType === "number") {
    return backendType as ContentType;
  }

  const typeMap: Record<string, ContentType> = {
    text: ContentType.Text,
    image: ContentType.Image,
    file: ContentType.File,
    url: ContentType.Url,
  };

  return typeMap[backendType.type] ?? ContentType.File;
}

/** Backend room role and capability contracts. */
export type { Capability, Grant, RoleDefinition } from '../types/generated/api.types';
import type { Capability, Grant, RoleDefinition } from '../types/generated/api.types';

/** 每个房间最多同时有效的 Editor 身份码数量（与后端 MAX_EDITOR_TOKENS 一致）。 */
export const MAX_EDITOR_TOKENS = 10;

export type BackendRoom = GeneratedRoomView;
export type CreateRoomResponse = GeneratedCreateRoomResponse;
export type RoomRole = RoleDefinition;
export type RoomGrant = Grant;
export type RoomCapability = Capability;

/**
 * Backend RoomContent response
 */
export type BackendRoomContent = GeneratedRoomContentView;

/**
 * Upload preparation response
 */
export type UploadPreparationResponse = GeneratedUploadPreparationResponse;

/**
 * Backend Token response (issue token)
 */
export type BackendTokenResponse = GeneratedIssueTokenResponse;

/**
 * Backend Token validation response
 */
export type BackendTokenValidation = GeneratedValidateTokenResponse;

// ============================================================================
// Frontend Types
// ============================================================================

export interface RoomSettings {
  expiresAt: string | null;
  passwordProtected: boolean;
  maxViews: number;
}

export interface RoomDetails {
  id: string;
  name: string;
  slug?: string; // Room slug (name for shareable, name_uuid for non-shareable)
  currentSize: number; // in bytes
  maxSize: number; // in bytes
  timesEntered: number;
  maxTimesEntered: number;
  settings: RoomSettings;
  defaultRoleKey: string;
  createdAt: string;
}

export interface Message {
  id: string;
  content: string;
  timestamp: string;
  updatedAt?: string;
  fileName?: string;
  user?: string;
  isOwn?: boolean;
  isNew?: boolean;
  isDirty?: boolean;
  isPendingDelete?: boolean;
  originalContent?: string;
  sequence_number?: number;
}

export type LocalMessage = Message;

export interface MessagePage {
  items: Message[];
  nextCursor: string | null;
  hasMore: boolean;
  nextSequenceNumber: number;
}

export interface FileItem {
  id: string;
  name: string;
  thumbnailUrl: string | null;
  size?: number; // in bytes
  type?: "image" | "video" | "pdf" | "link" | "document";
  url?: string;
  assetUrl?: string;
  description?: string;
  mimeType?: string;
  createdAt?: string;
  uploadedAt?: string;
  sequence_number?: number;
}

/**
 * Token information stored in localStorage
 */
export interface TokenInfo {
  token: string;
  expiresAt: string;
  refreshToken?: string;
  capabilities?: RoomGrant[];
  roleKey?: string;
}

/**
 * Token storage format (maps room name to token info)
 */
export type TokenStorage = Record<string, TokenInfo>;

export type Theme = "dark" | "light" | "system";

function bigintToNumber(value: bigint | number): number {
  return typeof value === "bigint" ? Number(value) : value;
}

/**
 * Convert backend Room to frontend RoomDetails.
 */
export function backendRoomToRoomDetails(room: BackendRoom): RoomDetails {
  return {
    id: String(room.id),
    name: room.name,
    slug: room.slug,
    currentSize: bigintToNumber(room.current_size),
    maxSize: bigintToNumber(room.max_size),
    timesEntered: bigintToNumber(room.current_times_entered),
    maxTimesEntered: bigintToNumber(room.max_times_entered),
    settings: {
      expiresAt: room.expire_at,
      passwordProtected: room.password_protected,
      maxViews: bigintToNumber(room.max_times_entered),
    },
    defaultRoleKey: room.default_role_key,
    createdAt: room.created_at,
  };
}

/**
 * Convert backend RoomContent to frontend Message (for text content)
 */
export function backendContentToMessage(content: BackendRoomContent): Message {
  // Ensure content.text is always a string
  let messageContent = "";
  if (content.text !== undefined && content.text !== null) {
    messageContent = typeof content.text === "string"
      ? content.text
      : String(content.text);
  }

  return {
    id: String(content.id),
    content: messageContent,
    timestamp: content.created_at,
    updatedAt: content.updated_at,
    fileName: content.file_name || undefined,
    sequence_number: content.sequence_number,
  };
}

/**
 * Convert backend RoomContent to frontend FileItem (for file content)
 */
export function backendContentToFileItem(
  content: BackendRoomContent,
  roomName?: string,
): FileItem {
  // Be defensive: some responses may not include content_type immediately
  const rawType = (content as any).content_type ?? (content as any).contentType;
  const contentType = parseContentType(rawType);

  const typeMap: Record<number, FileItem["type"]> = {
    [ContentType.Image]: "image",
    [ContentType.File]: "document",
    [ContentType.Url]: "link",
  };

  const isExternalLink = contentType === ContentType.Url;
  const fileUrl = isExternalLink
    ? (content.url ?? undefined)
    : buildContentPreviewPath(String(content.id));
  const assetUrl = isExternalLink
    ? (content.url ?? undefined)
    : buildContentAssetPath(String(content.id));

  return {
    id: String(content.id),
    name: content.file_name || "Unnamed",
    thumbnailUrl: null, // Backend doesn't provide thumbnails
    size: content.size || undefined,
    type: typeMap[contentType],
    url: fileUrl ?? undefined,
    assetUrl,
    description: isExternalLink ? content.text || undefined : undefined,
    mimeType: content.mime_type || undefined,
    createdAt: content.created_at,
    uploadedAt: content.created_at,
    sequence_number: content.sequence_number,
  };
}
