// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分块上传请求
 */
export type ChunkUploadRequest = { chunk_index: bigint, chunk_hash: string, };
