// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 管理凭证轮换请求（凭证不回显；覆盖仅存活于进程内，重启回退环境值）
 */
export type AdminCredentialUpdateRequest = { token: string, };
