// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 平台 dashboard 统计概览（issue #196）
 */
export type AdminStatsResponse = { rooms_total: number, rooms_open: number, rooms_protected: number, contents_total: number, contents_files: number, contents_messages: number, 
/**
 * 逻辑占用：内容记录字节数之和（含共享引用的重复计量）
 */
storage_logical_bytes: number, 
/**
 * 物理占用：内容寻址 blob 字节数之和（去重后）
 */
storage_physical_bytes: number, blob_count: number, active_connections: number, active_rooms: number, };
