// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 存储状态（不含任何凭据）
 */
export type AdminStorageResponse = { 
/**
 * "fs" | "s3"
 */
backend: string, 
/**
 * "proxy" | "presigned"
 */
transfer_mode: string, 
/**
 * backend = fs 时的存储根目录
 */
root: string | null, 
/**
 * backend = s3 时的桶名（不回显 endpoint 与凭据）
 */
bucket: string | null, presign_base_url: string | null, physical_bytes: number, logical_bytes: number, blob_count: number, 
/**
 * 逻辑与物理占用之差（去重节省）
 */
dedup_saved_bytes: number, };
