// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadFileDescriptor } from "./UploadFileDescriptor";

/**
 * 分块上传预留请求
 */
export type ChunkedUploadPreparationRequest = { files: Array<UploadFileDescriptor>, };
