// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReservedFileInfo } from "./ReservedFileInfo";

/**
 * 分块上传预留响应
 */
export type ChunkedUploadPreparationResponse = { 
/**
 * 预留 ID
 */
reservation_id: string, 
/**
 * 上传令牌
 */
upload_token: string, 
/**
 * 预留过期时间
 */
expires_at: string, 
/**
 * 文件清单
 */
files: Array<ReservedFileInfo>, };
