// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkStatus } from "./ChunkStatus";

/**
 * 单个分块状态信息
 */
export type ChunkStatusInfo = { 
/**
 * 分块索引
 */
chunk_index: number, 
/**
 * 分块大小
 */
chunk_size: number, 
/**
 * 分块哈希
 */
chunk_hash: string | null, 
/**
 * 上传状态
 */
upload_status: ChunkStatus, 
/**
 * 上传时间
 */
uploaded_at: string | null, };
