// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkStatus } from "./ChunkStatus";

/**
 * 分块上传响应
 */
export type ChunkUploadResponse = { chunk_index: number, upload_status: ChunkStatus, uploaded_chunks: number, total_chunks: number, upload_progress: number, };
