// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateRoomRequest = { 
/**
 * 可选房间密码。密码只在请求边界出现，不会在房间响应中回显。
 */
password?: string, };
