// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateRoomIdentityCodeRequest = { code: string, role: string, expires_in_secs: bigint | null, };
