// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Grant } from "./Grant";

export type CreateRoleRequest = { 
/**
 * 自定义角色 key（slug 形式）；系统角色 key 保留字，不可占用
 */
role_key: string, display_name: string, capabilities: Array<Grant>, };
