// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergedFileInfo } from "./MergedFileInfo";

/**
 * 文件合并完成响应
 */
export type FileMergeResponse = { reservation_id: string, merged_files: Array<MergedFileInfo>, message: string, };
