// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadPolicyMode } from "./DownloadPolicyMode";

export type FileDownloadPolicy = { id: number | null, content_id: number, mode: DownloadPolicyMode, max_downloads: number | null, download_count: number, created_at: string, updated_at: string, };
