// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 登出请求结构（撤销访问令牌）
 */
export type LogoutRequest = {
  /**
   * 访问令牌
   */
  access_token: string;
};
