// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicRoomConfig } from "./PublicRoomConfig";

export type PublicConfigResponse = { room: PublicRoomConfig, };
