// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Grant } from "./Grant";

/**
 * 刷新令牌验证响应结构
 */
export type RefreshTokenResponse = { 
/**
 * 新的访问令牌
 */
access_token: string, 
/**
 * 新的刷新令牌
 */
refresh_token: string, 
/**
 * 访问令牌过期时间
 */
access_token_expires_at: string, 
/**
 * 刷新令牌过期时间
 */
refresh_token_expires_at: string, 
/**
 * 刷新后的角色 key（角色归属随 refresh 旋转刷新）
 */
role: string, 
/**
 * 签发时解析得到的能力快照（非判定依据；判定以 DB room_roles 实时为准）
 */
capabilities: Array<Grant>, };
