// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 预留文件信息
 */
export type ReservedFileInfo = { 
/**
 * 文件名
 */
name: string, 
/**
 * 文件大小
 */
size: number, 
/**
 * MIME 类型
 */
mime: string | null, 
/**
 * 分块大小
 */
chunk_size: number, 
/**
 * 总分块数
 */
total_chunks: number, 
/**
 * 文件哈希
 */
file_hash: string | null, };
