// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";

export type RoomContentView = { id: number, content_type: ContentType, text: string | null, file_name: string | null, url: string | null, size: number | null, mime_type: string | null, created_at: string, updated_at: string, };
