// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";

export type RoomContentView = { id: number, content_type: ContentType, text: string | null, file_name: string | null, url: string | null, 
/**
 * 文件内容的相对下载路径（如 "/api/v1/contents/42"）。
 * 未包含任何凭据：房间 token 与下载票据仍由调用方按下载策略附加。
 */
download_url: string | null, size: number | null, mime_type: string | null, sequence_number: number, 
/**
 * 对外可见性；仅对拥有对应 visibility.manage 能力的身份有意义的标记
 */
hidden: boolean, 
/**
 * 创建者会话 jti（前端 own 作用域按钮判定用）
 */
created_by_jti?: string, created_at: string, updated_at: string, };
