// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenType } from "./TokenType";

export type RoomTokenClaims = { sub: string, room_id: number, room_name: string, 
/**
 * 会话绑定的角色 key（快照索引；能力判定永远以 DB room_roles 实时为准）
 */
role: string, max_size: number, exp: number, iat: number, jti: string, 
/**
 * 令牌类型
 */
token_type: TokenType, 
/**
 * 关联的刷新令牌 JTI（仅访问令牌包含此字段）
 */
refresh_jti?: string, };
