// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 房间刷新令牌数据模型
 * 用于存储和管理 JWT 刷新令牌的信息
 */
export type RoomRefreshToken = { 
/**
 * 主键 ID
 */
id: number | null, 
/**
 * 关联的房间 ID
 */
room_id: number, 
/**
 * 关联的访问令牌 JTI
 */
access_token_jti: string, 
/**
 * 刷新令牌的 SHA-256 哈希值（不存储明文）
 */
token_hash: string, 
/**
 * 刷新令牌过期时间
 */
expires_at: string, 
/**
 * 创建时间
 */
created_at: string, 
/**
 * 最后使用时间
 */
last_used_at: string | null, 
/**
 * 是否已撤销
 */
is_revoked: boolean, };
