// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomToken = { id: number | null, room_id: number, jti: string,
/**
 * 该会话绑定的角色 key（实时能力判定仍以 room_roles 为准）
 */
role_key?: string, expires_at: string, revoked_at: string | null, created_at: string, };
