// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomStatus } from "./RoomStatus";

export type RoomView = { id: bigint, name: string, slug: string, status: RoomStatus, max_size: bigint, current_size: bigint, max_times_entered: bigint, current_times_entered: bigint, expire_at: string | null, created_at: string, updated_at: string, permission: number, password_protected: boolean, };
