// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetContentVisibilityRequest = { 
/**
 * true = 隐藏（对外不可见）；false = 恢复显示
 */
hidden: boolean, };
