// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateRoomSettingsRequest = { 
/**
 * 房间密码（可选，设置为 None 表示移除密码）
 */
password?: string, 
/**
 * 房间有效期（可选，单位：秒；必须属于部署配置允许的期限）
 */
age_seconds?: number | null, 
/**
 * 最大进入次数（可选）
 */
max_times_entered?: number | null, 
/**
 * 最大容量限制（可选，单位：字节）
 */
max_size?: number | null, };
