// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 运行时可写配置更新（issue #196 白名单）；字段缺省 = 保持不变。
 */
export type UpdateRuntimeConfigRequest = { disallow_search_indexing: boolean | null, 
/**
 * 0 = 清除覆盖，回退配置文件默认值
 */
room_default_max_size: number, 
/**
 * 0 = 清除覆盖，回退配置文件默认值
 */
room_default_max_times_entered: number, };
