// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomContentView } from "./RoomContentView";

export type UpdateContentResponse = { updated: RoomContentView, };
