// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadFileTypePolicy } from "./UploadFileTypePolicy";

export type UpdateRoomSettingsRequest = { 
/**
 * 新房间密码。字段缺失表示保持当前密码不变。
 */
password?: string, 
/**
 * 显式移除当前房间密码，与 password 互斥。
 */
remove_password?: boolean, 
/**
 * 房间有效期（可选，单位：秒；必须属于部署配置允许的期限）
 */
age_seconds?: number | null, 
/**
 * 最大进入次数（可选）
 */
max_times_entered?: number | null, 
/**
 * 最大容量限制（可选，单位：字节）
 */
max_size?: number | null, 
/**
 * 新成员默认加入角色（可选；必须存在于本房角色集）
 */
default_role_key?: string, 
/**
 * 上传文件类型策略（可选；any 模式忽略扩展名列表，allow/deny 模式要求列表非空）
 */
upload_file_type?: UploadFileTypePolicy, };
