// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 客户端上报的文件信息
 */
export type UploadFileDescriptor = { name: string, size: number, mime?: string, chunk_size?: number, file_hash?: string, };
