// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 上传状态查询请求
 */
export type UploadStatusQuery = { 
/**
 * 上传令牌（与 reservation_id 二选一）
 */
upload_token?: string, 
/**
 * 预留 ID（与 upload_token 二选一）
 */
reservation_id?: string, };
