// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UploadPreparationResponse = { reservation_id: number, reserved_size: number, expires_at: string, current_size: number, remaining_size: number, max_size: number, };
