// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 客户端上报的文件信息
 */
export type UploadFileDescriptor = { name: string, size: number, mime: string | null, chunk_size: number | null, file_hash: string | null, };
