// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresignedUpload } from "./PresignedUpload";

export type UploadPreparationResponse = { reservation_id: number, reserved_size: number, expires_at: string, current_size: number, remaining_size: number, max_size: number, 
/**
 * presigned 传输模式下逐文件的直传 URL；proxy 模式为 None。
 */
presigned_uploads?: Array<PresignedUpload>, };
